---
- name: "fetch template for configuring system properties"
  set_fact:
    config_manager_text: "{{ lookup('config_template', 'configure_system_properties.j2') }}"
  when: system_properties
  delegate_to: localhost

- include_tasks: config_manager/load.yaml
  when: system_properties
