---
- name: initialize function
  include_tasks: includes/init.yaml

- name: collect platform capabilities as facts
  vyos_capabilities:

- name: run command and return configuration
  cli:
    command: "{{ vyos_config_source[source | default('running')] }}"
  register: configuration

- name: set configuration fact
  set_fact:
    configuration: "{{ configuration.stdout }}"

- name: parse system configuration
  command_parser:
    dir: "{{ role_path }}/parser_templates/config"
    content: "{{ configuration }}"