---
- name: initialize function
  include_tasks: includes/init.yaml

- name: collect platform capabilities as facts
  vyos_capabilities:

- name: run command and parse output
  include_tasks: includes/run_cli.yaml
  vars:
    vyos_command: "{{ item.command }}"
    vyos_parser: "cli/{{ item.parser }}"
    vyos_parser_engine: "{{ item.engine | default('command_parser') }}"
    vyos_run_cli_command_pre_hook: "{{ item.pre_hook | default(None) }}"
    vyos_run_cli_command_post_hook: "{{ item.post_hook | default(None) }}"

  loop: "{{ lookup('file', vyos_get_facts_command_map) | from_yaml }}"
  when: vyos_get_facts_subset | intersect(item.groups)
