---

- name: Set responder user fact to 'vyos' if not defined
  set_fact:
    cloud_vpn_responder_user: "{{ cloud_vpn_responder_user | default('vyos') }}"

- name: Set responder outside interface fact to 'eth0' if not defined
  set_fact:
    cloud_vpn_responder_outside_interface: "{{ cloud_vpn_responder_outside_interface | default('eth0') }}"
