# load task
#
- name: initialize function
  include_tasks: includes/init.yaml

- name: validate task arguments
  validate_role_spec:
    spec: config_manager/load.yaml

- name: validate config_manager_text is defined
  fail:
    msg: "missing required arg: config_manager_text"
  when: config_manager_text is undefined

- name: Include replace task
  include_tasks: includes/configure/replace.yaml
  when: vyos_config_replace
  vars:
    vyos_config_text: "{{ config_manager_text }}"

- name: Include configure task
  include_tasks: includes/configure/configure.yaml
  when: not vyos_config_replace
  vars:
    vyos_config_text: "{{ config_manager_text }}"
