# configure
#
- name: load configuration
  block:
    - name: enter configuration mode
      cli:
        command: configure

    - name: load configuration lines
      cli:
        command: "{{ line.strip() }}"
      loop: "{{ vyos_config_text | to_lines }}"
      loop_control:
        loop_var: line
      when: line not in vyos_config_ignore_keywords

    - name: compare
      cli:
        command: compare
      register: vyos_config_diff
      changed_when: vyos_config_diff.stdout

    - name: display config diff
      debug:
        msg: "{{ vyos_config_diff.stdout.splitlines() }}"

    - name: commit the configuration
      cli:
        command: commit
      when: not ansible_check_mode and vyos_config_commit_comment == "" and vyos_config_diff.stdout is not search("No changes")

    - name: commit the configuration with comment
      cli:
        command: "commit comment {{ vyos_config_commit_comment }}"
      when: not ansible_check_mode and vyos_config_commit_comment != "" and vyos_config_diff.stdout is not search("No changes")

    - name: discard when ansible_check_mode
      cli:
        command: discard
      when: ansible_check_mode

    - name: display message for check mode
      debug:
        msg: "Changes are not committed onto target device"
      when: ansible_check_mode

    - name: display message
      debug:
        msg: "Successfully loaded configuration onto target device"
      when: not ansible_check_mode and vyos_config_diff.stdout is not search("No changes")

    - name: leave configuration mode
      cli:
        command: exit

  rescue:
    - name: mark the host as failed
      fail:
        msg: "error loading configuration onto target device"
      when: not ansible_check_mode
      delegate_to: localhost
