---

- name: Push routing configuration to VyOS device
  vyos_config:
    src: "cloud_vpn/providers/vyos/initiator/{{ cloud_vpn_responder_provider }}/configure_routing_{{ cloud_vpn_routing }}.j2"
  delegate_to: initiator
